---
- set_fact:
    id: "{{ vpc | default('default') | hash('sha1') }}"

- name: create aws virtual private cloud
  amazon.aws.ec2_vpc_net:
    name: "vpc-{{ id[0:6] }}"
    region: "{{ aws_region }}"
    cidr_block: "{{ aws_vpc_cidr_block }}"
  register: aws_vpc

- name: create aws vpc subnet
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ aws_vpc.vpc.id }}"
    region: "{{ aws_region }}"
    cidr: "{{ item }}"
  with_items: "{{ aws_subnets | default([]) }}"
  register: aws_vpc_subnets

- name: create aws virtual private gateway
  community.aws.ec2_vpc_vgw:
    name: "vgw-{{ id[0:6] }}"
    region: "{{ aws_region }}"
    vpc_id: "{{ aws_vpc.vpc.id }}"
  register: aws_vpc_vgw
  when: aws_vpc_vgw_enabled | bool == True

- block:
    - name: create aws vpc route table
      community.aws.ec2_vpc_route_table:
        vpc_id: "{{ aws_vpc.vpc.id }}"
        region: "{{ aws_region }}"
        propagating_vgw_ids: [ "{{ aws_vgw.vgw.id | default(omit) }}" ]
        subnets: [ "{{ aws_vpc_subnet.subnet.id }}" ]
      register: aws_vpc_route_table
      when: aws_vpc_vgw_enabled | bool == True

    - name: create aws vpc route table
      community.aws.ec2_vpc_route_table:
        vpc_id: "{{ aws_vpc.vpc.id }}"
        region: "{{ aws_region }}"
        subnets: [ "{{ aws_vpc_subnet.subnet.id }}" ]
      register: aws_vpc_route_table
      when: aws_vpc_vgw_enabled | bool == False
  when: aws_vpc_route_table_enabled | bool == True
